// swift-tools-version:5.9
// Generated by publish.yml in Triple-Whale/triple-pixel-sdk@v0.1.1.
// Do not edit by hand — your changes will be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "TriplePixelSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "TriplePixelSDK", targets: ["TriplePixelSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "TriplePixelSDK",
            url: "https://github.com/Triple-Whale/triple-pixel-sdk-spm/releases/download/0.1.1/TriplePixelSDK.xcframework.zip",
            checksum: "e20d1e1aa52bd5443f58d74d1530d852ce1f830ee53d264c41c48f5c1c9aa375"
        ),
    ]
)
