// swift-tools-version:5.9
// Generated by publish.yml in Triple-Whale/triple-pixel-sdk@v0.1.3.
// Do not edit by hand — your changes will be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "TriplePixelSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "TriplePixelSDK", targets: ["TriplePixelSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "TriplePixelSDK",
            url: "https://github.com/Triple-Whale/triple-pixel-sdk-spm/releases/download/0.1.3/TriplePixelSDK.xcframework.zip",
            checksum: "96a7b2b9e4bd41aebe55c6e78cf1b268b5051eb6cde86b1797097e7c33bc663f"
        ),
    ]
)
