// swift-tools-version:5.9
// Generated by publish.yml in Triple-Whale/triple-pixel-sdk@v0.1.4.
// Do not edit by hand — your changes will be overwritten on the next release.

import PackageDescription

let package = Package(
    name: "TriplePixelSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "TriplePixelSDK", targets: ["TriplePixelSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "TriplePixelSDK",
            url: "https://github.com/Triple-Whale/triple-pixel-sdk-spm/releases/download/0.1.4/TriplePixelSDK.xcframework.zip",
            checksum: "df6a95c3f991e324f3a200a47108731735560d184c20b892a02d5c8ada3f24c9"
        ),
    ]
)
